---
title: "Indicadores Económicos"
output:
  flexdashboard::flex_dashboard:
     includes:
       in_header: header.html
     theme : yeti
     orientation : rows 
     css : coloresbotones.css
     self_contained : TRUE
     navbar:
       - { title: "Consultas y comentarios", href: "http://nahuelbargas.github.io/indeco/index.html", align: right}
       - { title: "Acceder al Dashboard", href: "http://nahuelbargas.github.io/indeco/indeco.html", align: left}
---



- Bienvenidos a la página que cree para compartir algunos  <a href="https://nahuelbargas.github.io/indeco/indeco.html"> indicadores económicos seleccionados </a>
de la república Argentina. 

- Mi nombre es Nahuel Bargas, tengo una licenciatura en Economía, y me 
interesan el análisis de datos, las estadísticas y 
las técnicas de visualización.


- En base a las librerías <a href="https://rstudio.github.io/flexdashboard"> Flexdashboard </a>,  <a href="http://rmarkdown.rstudio.com/"> Rmarkdown </a>, <a href="https://yihui.org/knitr/"> Knitr </a> ,  <a href="http://jkunst.com/highcharter/"> Highcharter </a> ,
entre otros paquetes del universo R, 
comparto un tablero actualizado con cuadros, gráficos dinámicos y 
tablas sobre la tasa de inflación, las estimaciones del producto interno bruto,
valor agregado bruto, desigualdad, pobreza, el resultado fiscal del sector público y la performance del comercio exterior 
argentino. 
Principalmente utilizó estimaciones y datos provistos por el INDEC, pero también en 
algunas secciones realizo mis propios cálculos. 
En el <a href="https://github.com/NahuelBargas/indeco"> repositorio <a/> podrán encontrar los códigos con los comandos utilizados, les pido que 
si el panel les resulta interesante, o les ayuda con sus propios proyectos, tengan la amabilidad de compartir mi trabajo.


- No duden en enviarme sus inquietudes o sugerencias al correo electrónico: nahuelbargas@hotmail.com  

- Cualquier comentario que sea útil para corregir o mejorar el sitio será muy valorado.

- También pueden contactarme en los siguientes medios,desde ya les agradezco por haberlo visitado.




```{css, echo=FALSE}

/*
Pueden dirigirse a http://janhuenermann.github.io/social-circles/ para 
conocer cómo implementar los botones para redes sociales en su documento.
En mi caso, adapte la fuente y css provistas por el autor para utilizar Ionicons.
Ver fonts/ionicons.ttf y css/social-circles.min2.css en mi repositorio.
*/


ol { 
        list-style-type: none;
        padding: 0;margin: 0;
}

ol li { 
        display: inline-block;
        margin: 4px;
}

.social-button.borderless {
        padding: 0 16px;
}


```


<ol>
	<li><a class="icon-linkedin social-button borderless" href="https://linkedin.com/in/nahuel-bargas/"></a></li>
    <li><a class="icon-twitter social-button borderless" href="https://twitter.com/Nahuel_Sef"></a></li>
	<li><a class="icon-github social-button borderless" href="https://github.com/NahuelBargas"></a></li>
    <li><a class="icon-telegram social-button borderless" href="https://telegram.me/Nahuel_Sef"></a></li>
</ol>

